"""add mission and target

Revision ID: ac7bed9fa87b
Revises: e624eb9b7f96
Create Date: 2024-12-02 16:40:10.518166

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ac7bed9fa87b"
down_revision: Union[str, None] = "e624eb9b7f96"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "missions",
        sa.Column("cat_uuid", sa.UUID(), nullable=True),
        sa.Column("is_completed", sa.Boolean(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["cat_uuid"],
            ["cats.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("cat_uuid", name="unique_mission_per_cat"),
    )
    op.create_table(
        "targets",
        sa.Column("mission_id", sa.UUID(), nullable=True),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("country", sa.String(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("complete", sa.Boolean(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["mission_id"],
            ["missions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.alter_column(
        "cats",
        "id",
        existing_type=sa.NUMERIC(),
        type_=sa.UUID(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "cats",
        "id",
        existing_type=sa.UUID(),
        type_=sa.NUMERIC(),
        existing_nullable=False,
    )
    op.drop_table("targets")
    op.drop_table("missions")
    # ### end Alembic commands ###
